module.exports = {
    "+ccc": require("./lookup"),
    "!bonk": require("./bonk"),
    "!compliment": require("./compliment"),
    "!dadjoke": require("./dadjoke"),
    "!edit": require("./edit"),
    "!saint": require("./saints"),
    "!remindme": require("./remindme"),
    "!vacate": require("./vacate"),
    "!say": require("./say"),
    // "!studybreak": require("./studybreak"),
    "!chanTimer": require("./chanTimer"),
    "!prune-intros": require("./pruneIntros"),
    "!quarantine": require("./quarantine"),
};
